### PR TITLE
fix: put the binary under bin directly

### PR DESCRIPTION
**Pull request by frostming**
Put the binary under the `bin` directly, instead of using a python wrapper script. This will reduce the overhead of invoking a program and will gain a performance improvement of the bootstrap of ~3 times

```
❯ time venv1/bin/envd version
envd: v0.2.5-rc.1+c7fd12b.dirty
  BuildDate: 2022-12-02T07:10:14Z
  GitCommit: c7fd12b9047b5c59e555a3d083cdf7cdef1449d6
  GitTreeState: dirty
  GitTag: v0.2.5-rc.1
  GoVersion: go1.19.2
  Compiler: gc
  Platform: darwin/arm64
venv1/bin/envd version  0.07s user 0.04s system 46% cpu 0.248 total
❯ time venv2/bin/envd version
envd: v0.2.5-rc.1+c7fd12b.dirty
  BuildDate: 2022-12-02T07:45:20Z
  GitCommit: c7fd12b9047b5c59e555a3d083cdf7cdef1449d6
  GitTreeState: dirty
  GoVersion: go1.19.2
  Compiler: gc
  Platform: darwin/arm64
venv2/bin/envd version  0.01s user 0.03s system 48% cpu 0.078 total
```

### CODE REVIEW

**Comment by kemingy** [comment]
Amazing! Thanks for your PR @frostming.

I don't know `<wheel>/data/bin` is a special directory. Is there any document?

**Review by kemingy — APPROVED** [review]

**Comment by frostming** [comment]
> Amazing! Thanks for your PR @frostming.
> 
> I don't know `<wheel>/data/bin` is a special directory. Is there any document?

Yes, https://peps.python.org/pep-0491/#the-data-directory

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by gaocegege** [comment]
@all-contributors Please add @frostming for the code contribution.

**Pull request merged**
