### PR TITLE
feat(docker): Add entrypoint and ports in image config

### PR DESCRIPTION
**Pull request by gaocegege**
Ref #303 

This PR is to add entrypoints and exposed ports into the image config.

EXPOSE and ENTRYPOINT instruction doesn’t actually exposes port and sets entrypoint to the external environment, it acts as documentation between person who’s writing Dockerfile and person who’s running Dockerfile.

Signed-off-by: Ce Gao <cegao@tensorchord.ai>

### CODE REVIEW

**Comment by gaocegege** [comment]
> So the port/entrypoint configuration is not exposed to the user yet?

Yep, they are exposed to the people who run the images. But if you are the end-user, you do not need to deal with these things

And, we can remove port in `config.jupyter`. We will use a random host port to forward.

**Comment by VoVAllen** [comment]
> > So the port/entrypoint configuration is not exposed to the user yet?
> 
> Yep, they are exposed to the people who run the images. But if you are the end-user, you do not need to deal with these things
> 
> And, we can remove port in `config.jupyter`. We will use a random host port to forward.

Is it still configureable？

**Comment by gaocegege** [comment]
No, the port does not work after the PR. Actually, there is no need to specify the port since we can choose a random one, just like ssh does.

**Comment by gaocegege** [comment]
Please see the change https://github.com/tensorchord/envd/pull/533/commits/8f384cc39814c7da0bdbf152033cfcb7518f96b9

@VoVAllen

**Pull request merged**
