### PR TITLE
feat: dynamic test split and run

### LINKED ISSUE #1248: feat: make e2e test faster
## Description

Solution:
* split into different action jobs
* option: check if we can run all the ginkgo Describe parallel with GitHub Actions

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by cutecutecat**
Signed-off-by: cutecutecat <starkind1997@gmail.com>

close #1248

### CODE REVIEW

**Comment by cutecutecat** [comment]
It seems bad for run `It` parallel, as some test dependency will be destroyed.
https://github.com/tensorchord/envd/blob/f7f2b34a80f616ae4db1c0fdb1c01f6583f4821f/e2e/v0/cli/init_test.go#L53

relys

https://github.com/tensorchord/envd/blob/f7f2b34a80f616ae4db1c0fdb1c01f6583f4821f/e2e/v0/cli/init_test.go#L44

And it seems couldn't accelerate into 10 min. I would try make a parallel of files.

**Comment by cutecutecat** [comment]
use `ginkgo` arg `-p` to parallel two test files in one job will cause `failed to initialize cache: failed to decode cache map: EOF`, abandon.

ref:
https://github.com/tensorchord/envd/actions/runs/3667160941/jobs/6199440940

**Comment by cutecutecat** [comment]
ginkgo run argument `--coverpkg` need to be revised from `./pkg/...`, as it will ruin the releative path.

**Comment by cutecutecat** [comment]
We would do a upgrad of Ginkgo to fix:
```
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
  Ginkgo CLI Version:
    2.6.0
  Mismatched package versions found:
    2.5.1 used by cli, docs, language, cli, docs, language
```

**Comment by cutecutecat** [comment]
The finally running time ranges from 12-14min, it is nearly impossible to accelerated into 10 min, as some of the tests take up to nearly 300s.

For example:
`e2e/v1/language/python_conda_test.go` takes 372.342s in one run, and it could not be splitted more.

Two of them on one job will lead to time cost beyond 10min, so I set a warning for this case when more tests in the future:
```python
if average_workload > 2:
    logging.info(
            "average tests carried per job[{average_workload}] > 2, "
            "as maximum time of estimated test case may be 300s, "
            "we recommend to increase ci_total to make total time less than 10min"
        )

```

**Comment by kemingy** [comment]
> The finally running time ranges from 12-14min, it is nearly impossible to accelerated into 10 min, as some of the tests take up to nearly 300s.

As a comparison, the last merged PR takes 12-16min to run the tests https://github.com/tensorchord/envd/actions/runs/3653806802. I think the cache also helps (I haven't evaluated it yet).

**Comment by cutecutecat** [comment]
> > The finally running time ranges from 12-14min, it is nearly impossible to accelerated into 10 min, as some of the tests take up to nearly 300s.
> 
> As a comparison, the last merged PR takes 12-16min to run the tests https://github.com/tensorchord/envd/actions/runs/3653806802. I think the cache also helps (I haven't evaluated it yet).

Sorry about it, I have used `Total duration` for standard, if we only compare `run the tests` job, it could defenitely be 11min-12min.
And for previous tests arrangement, it could up to 20min for the same PR, I think we still have a good effect.
https://github.com/tensorchord/envd/actions/runs/3661943658

Never mind, I would do a survey about how we can make use of cache in different jobs tomorrow, though it might be hard, I will try.

**Comment by cutecutecat** [comment]
We could export buildkit cache to Github Action cache when running e2e test.
ref:
https://github.com/moby/buildkit/issues/2885
https://github.com/docker/build-push-action/issues/624

**Comment by cutecutecat** [comment]
> > We could export buildkit cache to Github Action cache when running e2e test. ref: [moby/buildkit#2885](https://github.com/moby/buildkit/issues/2885) [docker/build-push-action#624](https://github.com/docker/build-push-action/issues/624)
> 
> I remember it will exceed the cache size limit. But you can try.

I found a new solution, we could use a `organize package` as cache, and make a bot account to login it to sync cache.
Then we will have unlimited "cache".

When at `push/merge`, we call it `safe mode` and do `import/export` cache to packages.
When at `push request`, we call it `unsafe mode` and do `import` cache from packages.

The packages are at:
https://github.com/orgs/envd-cache/packages/container/package/e2e-test
The robot account:
https://github.com/cat-deploy-unsafe

I will test this way and need the write access to set two secret `TEST_CACHE_BOT` and `TEST_CACHE_BOT_TOKEN` to enable all of above.

**Comment by cutecutecat** [comment]
> The time still is ~10 minutes. And the code is complex. Should we keep it simple if the benefit is not significant?

The most time-cost job is `e2e/v1/language/python_conda_channel_test`

#48 exporting to oci image format
#48 exporting layers
#48 exporting layers 53.3s done
#48 exporting manifest sha256:6f29186ec9328cefd7b49edd26f0049b08be40b954e08eb7d1e81697edb0917c done
#48 exporting config sha256:aa8fad0a552eacadb08b57de3f1b3f45680489258a231069c3118b0d81951f40 done
#48 sending tarball
#48 sending tarball 48.0s done
#48 DONE 101.4s

• [350.307 seconds]

Could we prevent buildkit from uploading the oci artifact?

**Comment by gaocegege** [comment]
The image is not pushed to registry. A docker load is executed to load the artifact to local docker daemon. I think it is necessary.

Thus we cannot disable this behavior.

**Comment by gaocegege** [comment]
But we can update e2e/v0/language/testdata/python/conda_channel/env.yaml to install a small package, e.g. via.

/cc @cutecutecat

**Comment by cutecutecat** [comment]
This is the final version, I have use a small package `fastchan/libblas` instead of `dglteam/dgl`. I made 4 try on it:

import+export cache: 7m 52s
https://github.com/cutecutecat/envd/actions/runs/3676211293/attempts/1

only import cache 1st: 8m 57s
https://github.com/cutecutecat/envd/actions/runs/3676211293/attempts/2

only import cache 2st: 7m 48s
https://github.com/cutecutecat/envd/actions/runs/3676211293

only import cache this PR: 9m 20s
https://github.com/tensorchord/envd/actions/runs/3676211777

I am not sure whether it's significant.

/cc @gaocegege @kemingy

**Comment by kemingy** [comment]
> This is the final version, I have use a small package `fastchan/libblas` instead of `dglteam/dgl`.

`dgl` is chosen for a certain reason. It's only available in the `dglteam` channel. While `libblas` appears in lots of channels. I'm not sure if there is a suitable replacement that is smaller.

**Comment by cutecutecat** [comment]
> > This is the final version, I have use a small package `fastchan/libblas` instead of `dglteam/dgl`.
> 
> `dgl` is chosen for a certain reason. It's only available in the `dglteam` channel. While `libblas` appears in lots of channels. I'm not sure if there is a suitable replacement that is smaller.

Ok, I could use `bioconda/bioconda-repodata-patches` instead tomorrow, it also met this requirement and it is as small as 1.4M

**Comment by cutecutecat** [comment]
The file based load-balance is removed.
The repo remote cache is removed.

Now we have:
- change dgl into bioconda-repodata-patches

And another refactor:
- remove hardcoded makefile targets

The first time cost of whole `CI` is 15min 0s.
I would run it again by force-push.

**Review by kemingy — APPROVED** [review]
/lgtm

**Pull request closed without merging**
