### PR TITLE
feat: Support set environment name in `envd up` command

### PR DESCRIPTION
**Pull request by Zheaoli**

### CODE REVIEW

**Comment by aseaday** [comment]
Is `StringFlag`'s default value to `""` defined or undefined which may break someday in the future?

**Comment by aseaday** [comment]
Please check my comment and other parts LGTM.

**Comment by kemingy** [comment]
Actually, `-t` is the environment name.

**Comment by Zheaoli** [comment]
> Actually, `-t` is the environment name.

I think `-t` is not working for env name. FYI https://github.com/tensorchord/envd/blob/main/pkg/app/up.go#L210

**Comment by kemingy** [comment]
But I think there is a bug for `-t`. If you also set it to `envd up -t test:latest` then you cannot destroy it because `envd destroy --name xxx` doesn't accept the tag. :(

**Comment by Zheaoli** [comment]
All comment has been addressed, PTAL

**Comment by aseaday** [comment]
> But I think there is a bug for `-t`. If you also set it to `envd up -t test:latest` then you cannot destroy it because `envd destroy --name xxx` doesn't accept the tag. :(

Good question. I also have the confusion among the tag, image and the env

**Comment by suyanhanx** [comment]
It looks confusing. Other commands use another different flag to indicate the name.
https://github.com/tensorchord/envd/blob/a4f7a5ca824d2ce375b01fb61bfe3c1e48aef3b2/pkg/app/pause.go#L26-L35

I think "name" would be a better option as a flag to indicate the name. 
The "-t"/tag seems more appropriate for images.

Or to put it another way, the concept of "tag" does not seem to be appropriate for defining environments. `test:latest` can already be a complete name, can't it?

**Comment by kemingy** [comment]
> I think "name" would be a better option as a flag to indicate the name. The "-t"/tag seems more appropriate for images.
> 
> Or to put it another way, the concept of "tag" does not seem to be appropriate for defining environments. `test:latest` can already be a complete name, can't it?

Agree. I think we need to align the naming.

**Comment by Zheaoli** [comment]
so, is there any final decision about this PR?

**Comment by kemingy** [comment]
cc @gaocegege

**Review by kemingy — APPROVED** [review]

**Comment by kemingy** [comment]
I misunderstood. It's the `environment` name, not the image name. The code has so many *name* things.

**Pull request merged**
