### PR TITLE
feat(CI): add nightly build & test tasks

### LINKED ISSUE #361: feat(CI): Nightly build
## Description

We can support nightly builds now.

### PR DESCRIPTION
**Pull request by Triple-Z**
resolves #361

Signed-off-by: Triple-Z <me@triplez.cn>

### CODE REVIEW

**Comment by Triple-Z** [comment]
The `nightly.yml` GH Action config is valid and [passed](https://github.com/Triple-Z/envd/actions/runs/3226823249).

**Review by gaocegege — APPROVED** [review]
/lgtm

Thanks for your contribution! :tada: :+1:

**Pull request merged**
