### PR TITLE
chore: fix typo and format imports and simplify code

### PR DESCRIPTION
**Pull request by hezhizhen**
Signed-off-by: Zhizhen He <hezhizhen.yi@gmail.com>

### CODE REVIEW

**Comment by hezhizhen** [comment]
Sorry to make it a large PR, but all the changes are trivial, and I've checked every change on GitHub manually. Please take a look at it.

**Review by terrytangyuan — APPROVED** [review]
LGTM!

**Comment by gaocegege** [comment]
@hezhizhen I am wondering if the `cli` is removed by gofmt?

**Comment by gaocegege** [comment]
@al-contributors Please add @hezhizhen for doc contribution.

**Comment by gaocegege** [comment]
@all-contributors Please add @hezhizhen for doc contribution.

**Comment by hezhizhen** [comment]
> @hezhizhen I am wondering if the `cli` is removed by gofmt?

I use GoLand which has an option about imports called `Remove redundant import aliases` and every time I save Go files, they will be formatted and redundant import aliases will be removed.

**Comment by gaocegege** [comment]
OK SGTM.

The alias is actually auto-added by vscode golang extension :smile:

**Pull request merged**
