### PR TITLE
fix: pypi sdist

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingy94@gmail.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
```
        - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
```

We need to update it, I will do it.

**Comment by gaocegege** [comment]
Please rebase and give it another try.

**Comment by kemingy** [comment]
> Please rebase and give it another try.

Fixed. @VoVAllen please take a look.

**Review by VoVAllen — APPROVED** [review]
thanks!

**Comment by kemingy** [comment]
Will the bot automatically merge the approved PR? @gaocegege I don't have the permission.

**Pull request merged**
