### PR TITLE
fix: add auto start buildkit container

### PR DESCRIPTION
**Pull request by aseaday**
Signed-off-by: Qi Chen <aseaday@hotmail.com>

### CODE REVIEW

**Comment by aseaday** [comment]
This is the first patch of https://github.com/tensorchord/envd/issues/561.
We may need more talk.

**Review by gaocegege — COMMENTED** [review]
The approach LGTM.

/cc @kemingy @VoVAllen

**Comment by aseaday** [comment]
> This is the first patch of #561. We may need more talk.

Add rp restart always for current stage workaround.

**Comment by gaocegege** [comment]
LGTM, I am merging it.

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Pull request merged**
