### PR TITLE
chore: Update README to expand the scope

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <cegao@tensorchord.ai>

### CODE REVIEW

**Review by kemingy — APPROVED** [review]
/lgtm

**Comment by kemingy** [comment]
I think there are still some AI or ML in the README. Do you want to replace all of them?

BTW, we already support golang :rofl: 

The installation method may need to be extended.

**Comment by gaocegege** [comment]
> The installation method may need to be extended.

Let's keep it.

I updated other sections. PTAL

**Review by kemingy — APPROVED** [review]

**Pull request closed without merging**
