### PR TITLE
chore: fix zsh prompt

### LINKED ISSUE #617: feature: Correct PROMPT prefix in the container terminal
## Description

```console
❯ envd up                                                                                                                            (base)
[+] ⌚ parse build.envd and download/cache dependencies 0.0s ✅ (finished)
 => 💽 (cached) download oh-my-zsh                                                                                                      0.0s
[+] build envd environment 203.8s (31/31) FINISHED
 => local://cache-dir                                                                                                                  0.5s
 => => transferring cache-dir: 426.41kB                                                                                                0.5s
 => docker-image://docker.io/tensorchord/python:3.8-ubuntu20.04                                                                        8.9s
 => => resolve docker.io/tensorchord/python:3.8-ubuntu20.04                                                                            8.9s
 => CACHED [internal] create user group envd                                                                                           0.0s
 => CACHED [internal] create user envd                                                                                                 0.0s
 => CACHED [internal] add user envd to sudoers                                                                                         0.0s
 => CACHED [internal] configure user permissions                                                                                       0.0s
 => CACHED [internal] configure user permissions                                                                                       0.0s
 => CACHED copy /oh-my-zsh /home/envd/.oh-my-zsh                                                                                       0.0s
 => CACHED mkfile /home/envd/install.sh                                                                                                0.0s
 => CACHED install oh-my-zsh                                                                                                           0.0s
 => CACHED mkfile /home/envd/.zshrc                                                                                                    0.0s
 => CACHED [internal] initialize conda bash environment                                                                                0.0s
 => CACHED [internal] create conda environment                                                                                         0.0s
 => CACHED [internal] initialize conda zsh environment                                                                                 0.0s
 => CACHED [internal] add conda environment to zshrc                                                                                   0.0s
 => CACHED [internal] create cache dir                                                                                                 0.0s
 => CACHED [internal] settings pip cache mount permissions                                                                             0.0s
 => CACHED mkdir /var/envd                                                                                                             0.0s
 => CACHED install ssh keys                                                                                                            0.0s
 => CACHED install ssh keys                                                                                                            0.0s
 => CACHED install system packages                                                                                                     0.0s
 => CACHED install conda packages                                                                                                      0.0s
 => pip install numpy                                                                                                                 18.5s
 => install PyPI packages                                                                                                              0.2s
 => merging all components into one                                                                                                  137.7s
 => => merging                                                                                                                       137.7s
 => update alternative python to envd                                                                                                  8.4s
 => update alternative python to envd                                                                                                  2.6s
 => update alternative python to envd                                                                                                  2.5s
 => update alternative python to envd                                                                                                  2.5s
 => mkfile /home/envd/.gitconfig                                                                                                       2.4s
 => exporting to oci image format                                                                                                     19.2s
 => => exporting layers                                                                                                               16.2s
 => => exporting manifest sha256:f604733ea4336a32be908470ad658e037b2183cae39ad66031e716435f494ba5                                      0.0s
 => => exporting config sha256:8136afd207792423d2682a75f3183ea937adbbb079412d97ff05253dae55c112                                        0.0s
 => => sending tarball                                                                                                                 3.0s
(envd) (envd) ➜  quick-start git:(master) ls
LICENSE  README.md  build.envd  demo.py
(envd) (envd) ➜  quick-start git:(master)
```

## Reproduction

run `envd up` with the `envd-quick-start`

## Additional Info

I guess one is `zsh` PROMPT, another is `conda` PROMPT.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

* fix #617 

ref to:
* https://gist.github.com/romkatv/2a107ef9314f0d5f76563725b42f7cab
* https://superuser.com/a/974942
* https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Prompt-Themes

To try this new zsh theme, you may need to run `envd prune && rm -rf $HOME/.cache/envd`

image

### CODE REVIEW

**Comment by aseaday** [comment]
I thought it was a feature before....

**Comment by gaocegege** [comment]
We want to show `(envd)` instead of `(envd)(envd)` in zsh. Now we always activate conda, thus `(envd)(envd)` is shown.

**Comment by gaocegege** [comment]
Should we open it since we already have #681 ?

**Comment by kemingy** [comment]
> Should we open it since we already have #681 ?

Yes.

* close this since we have a better solution in #681

**Pull request closed without merging**
