### PR TITLE
feat: add typos to pre-commit and GitHub action

### PR DESCRIPTION
**Pull request by hezhizhen**
Add https://github.com/crate-ci/typos to lint typos.

### CODE REVIEW

**Comment by gaocegege** [comment]
Awesome!

**Comment by hezhizhen** [comment]
I'm still fixing typos, so please wait for a while.

**Comment by hezhizhen** [comment]
> I'm still fixing typos, so please wait for a while.

Done. PTAL @kemingy @gaocegege 

The modification for svgs is `Data Scientis` -> `Data Scientists`. If it's not appropriate, please let me know and I'll change it.

**Review by kemingy — APPROVED** [review]
/lgtm

**Comment by gaocegege** [comment]
/lgtm

Thanks for your contribution! :tada: :+1:

**Comment by hezhizhen** [comment]
The `e2e-lang` job in CI takes too much time. Maybe it should be optimized to reduce its execution time?

**Comment by kemingy** [comment]
> The `e2e-lang` job in CI takes too much time. Maybe it should be optimized to reduce its execution time?

It's not stable recently. Not sure why.

We used to optimize the e2e in https://github.com/tensorchord/envd/pull/1288, but didn't meet our expectations. Feel free to take a look.

**Pull request merged**
