### PR TITLE
feat: add progress bar for `envd up` and `envd run`

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

* fix https://github.com/tensorchord/envd/issues/1413

To align the `envd up` and `envd run`, the progress bar is used for the environment creation. I didn't add the progress bar for the docker load from the pipe. (hope we can get rid of it with the newer moby https://github.com/moby/moby/releases/tag/v20.10.23)

### CODE REVIEW

**Comment by kemingy** [comment]
You can preview it here:

[asciicast](https://asciinema.org/a/MgEcm1uSzu0YhSU2a9x5OBHr5)

**Comment by gaocegege** [comment]
It's awesome! Could you please fix the test failures?

**Comment by kemingy** [comment]
- blocked by https://github.com/schollz/progressbar/pull/153

**Comment by suyanhanx** [comment]
There are two display modes, one keeps completed steps and the second doesn't. 
We can discuss which one to choose.

**Comment by kemingy** [comment]
> There are two display modes, one keeps completed steps and the second doesn't. We can discuss which one to choose.

Yes. I think it's okay to keep it since it will show how much time these steps cost.

**Review by gaocegege — APPROVED** [review]

**Pull request merged**
