### PR TITLE
docs: v1 r_lang and julia packages

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

One more thing, only `install.julia_packages` use `names` instead of `name`. Shall we align them? cc @VoVAllen @gaocegege

### CODE REVIEW

**Comment by gaocegege** [comment]
I think we should.

**Comment by kemingy** [comment]
> I think we should.

Do you mean changing to `names` or `name` in v1?

**Comment by gaocegege** [comment]
> > I think we should.
> 
> Do you mean changing to `names` or `name` in v1?

Yep

**Comment by gaocegege** [comment]
names

**Comment by kemingy** [comment]
> names could be name

Fixed. PTAL.

**Review by gaocegege — APPROVED** [review]

**Pull request merged**
