### PR TITLE
chore: add unconvert to linters and address related issues

### PR DESCRIPTION
**Pull request by hezhizhen**
Fixed some typo by the way.

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
/cc @kemingy

**Review by kemingy — APPROVED** [review]
LGTM. How can we fix the lint error? @gaocegege

**Comment by gaocegege** [comment]
I think we could comment the lint for now. I did not fix such issue before.

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Pull request merged**
