### PR TITLE
feat(lang): init py env by generating the bulid.envd

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

includes:
* requirements.txt
* env.yaml

maybe later:
* pyproject.toml
* setup.cfg
* setup.py

### CODE REVIEW

**Comment by aseaday** [comment]
Could we test it under root users?

**Comment by kemingy** [comment]
> Could we test it under root users?

What do you mean by "under root users"? Run the `envd init` with `sudo`?

**Review by gaocegege — APPROVED** [review]

**Comment by aseaday** [comment]
> > Could we test it under root users?
> 
> What do you mean by "under root users"? Run the `envd init` with `sudo`?

such as 
```bash
# envd init
```

**Comment by kemingy** [comment]
> > > Could we test it under root users?
> > 
> > 
> > What do you mean by "under root users"? Run the `envd init` with `sudo`?
> 
> such as
> 
> ```shell
> # envd init
> ```
> 
> sometimes ,root users executions will cause some unexpected error for file permission.

Is it related to https://github.com/tensorchord/envd/issues/666?

Do we need to add the root test to all the e2e tests?

**Comment by aseaday** [comment]
> > > > Could we test it under root users?
> > > 
> > > 
> > > What do you mean by "under root users"? Run the `envd init` with `sudo`?
> > 
> > 
> > such as
> > ```shell
> > # envd init
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sometimes ,root users executions will cause some unexpected error for file permission.
> 
> Is it related to #666?
> 
> Do we need to add the root test to all the e2e tests?

I think we could do all e2e tests in root users. WDYT @gaocegege

**Review by aseaday — APPROVED** [review]
LGTM, e2e root test under root could be a CI task

**Comment by kemingy** [comment]
I'm going to merge this one. We can discuss the root user test in #666.

**Pull request merged**
