### PR TITLE
fix: Remove dump checkout and remove pre-commit

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <cegao@tensorchord.ai>

### CODE REVIEW

**Comment by gaocegege** [comment]
@hawkingrei 

noloopclosure is not merged in v1.50, thus we cannot use it now.

Ref https://github.com/golangci/golangci-lint/pull/3027

**Comment by gaocegege** [comment]
I removed the pre-commit here because it is buggy. golang lint will not run if only .github/flows are changed. Thus we do not know if the change to golangci-lint works.

**Comment by hawkingrei** [comment]
Of course， ```noloopclosure``` is a good linter. it has been enabled in the TiDB repo. it can be enabled when is merged into the golangci-linter.

**Comment by gaocegege** [comment]
I will open an issue to keep track of it.

**Review by VoVAllen — APPROVED** [review]
LGTM. What's the difference comparing to the original lint?

**Comment by gaocegege** [comment]
The golangci-lint action will be run every time.

The previous implementation only run when the file changed.

**Review by kemingy — APPROVED** [review]
\lgtm

**Pull request merged**
