### PR TITLE
Example: add cpu example

### PR DESCRIPTION
**Pull request by VoVAllen**
Add cpu example & use it as default

### CODE REVIEW

**Comment by VoVAllen** [comment]
Later we might want to enable the grammar of `envd up -f buid.envd:build_gpu` for build GPU, and we'll have one envd file looks like 
```
def build():
    base(os="ubuntu20.04", language="python3")
    install.vscode_extensions([
        "ms-python.python",
    ])

    install.python_packages([
        "tensorflow",
        "numpy",
    ])
    install.cuda(version="11.6", cudnn="8")
    shell("zsh")
    config.jupyter(password="", port=8888)

def build_gpu():
    build()    
    install.cuda(version="11.6", cudnn="8")
```

**Comment by terrytangyuan** [comment]
> Later we might want to enable the grammar of `envd up -f :build_gpu` to build with cuda, and we'll have one single envd file looks like

Relevant issue https://github.com/tensorchord/envd/issues/246. `--no-gpu` seems handy but may not be generic for other use cases. WDYT @gaocegege @VoVAllen?

**Comment by gaocegege** [comment]
@VoVAllen I think the gpu example code in TF is only run on GPUs. Could you please verify if it can be run on CPUs?

**Comment by gaocegege** [comment]
> Relevant issue https://github.com/tensorchord/envd/issues/246. --no-gpu seems handy but may not be generic for other use cases. WDYT @gaocegege @VoVAllen?

Yep, I think we can use a flag here

**Comment by VoVAllen** [comment]
I tested it works with cpu. Tensorflow can automatically switch between CPU and GPU since it doesn't have explicit device placement

**Comment by gaocegege** [comment]
LGTM. 

Please rebase.

**Comment by VoVAllen** [comment]
rebased to master

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Pull request merged**
