### PR TITLE
feat(CLI): Support run command

### PR DESCRIPTION
**Pull request by gaocegege**
Ref #11 

```
NAME:
   envd run - Spawns a command installed into the environment.

USAGE:
   envd run [command options] [arguments...]

OPTIONS:
   --command value, -c value  Command to execute
   --name value, -n value     Name of the environment
```

```
$ envd run --name python-basic --command "pip list"
Package            Version
------------------ ---------
certifi            2022.6.15
charset-normalizer 2.1.0
idna               3.3
pip                22.1.2
requests           2.28.1
setuptools         61.2.0
urllib3            1.26.10
via                0.0.2
wheel              0.37.1
```

Signed-off-by: Ce Gao <cegao@tensorchord.ai>

### CODE REVIEW

**Comment by aseaday** [comment]
The Implementation is good to me. But should we use `run` or `exec`?

**Comment by gaocegege** [comment]
pipenv uses run, docker uses exec. I think run is easy to understand by users.

**Comment by kemingy** [comment]
I prefer `run` because it's easier to type.

**Comment by aseaday** [comment]
> pipenv uses run, docker uses exec. I think run is easy to understand by users. WDYT @aseaday

Got it. LGTM

**Review by aseaday — APPROVED** [review]

**Pull request merged**
