### PR TITLE
chore: update image in readme

### PR DESCRIPTION
**Pull request by lilylee1874**

### CODE REVIEW

**Comment by gaocegege** [comment]
https://github.com/lilylee1874/envd Preview is here.

WDYT 

@kemingy @VoVAllen

**Comment by kemingy** [comment]
The image looks good but I'm not sure if we should put two images together at the beginning. Maybe we can adjust the position?

**Comment by VoVAllen** [comment]
I like the blue theme color! 

Minor suggestions:
- Include container or similar metaphor in the ML App icon. Since we focus on container a lot
- Merge the head envd cat with the new icon together. Two lines of icons looks too empty at first glance. For example, envd cat can "eat" those frameworks? (sounds weird, just a crazy idea)

**Comment by VoVAllen** [comment]
Or something like nyan cat? Put frameworks at left and `ML App` at right?

image

**Comment by zwpaper** [comment]
the logo below(red square one) seems better than the one above(blue), how about also changing the above one logo?

image

**Comment by zwpaper** [comment]
> Merge the head envd cat with the new icon together. Two lines of icons looks too empty at first glance

@VoVAllen maybe it would be better to change the location of the second image? one highlight logo for README may be important to newcomers.

**Comment by zwpaper** [comment]
did some adjustments to change the image location

PS forgive me for the poor image editing, I was at kindergarten level

Xnip2022-10-05_18-01-10

**Comment by lilylee1874** [comment]
> Xnip2022-10-05_18-01-10

this structure looks good.
We need to rerender the gif. if we want to update the main Logo image, need more time.

**Comment by gaocegege** [comment]
The current layout LGTM.

/cc @VoVAllen @kemingy @zwpaper

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Pull request merged**
