### PR TITLE
Remove incorrect `sudo` command when installing system package

### PR DESCRIPTION
**Pull request by oubotong**
In the function `compileSystemPackages()`, the `sudo` before `apt-get install` prevent the base environment configuration from taking effect (such as `DEBIAN_FRONTEND=noninteractive` setting). 

This would result in the container being blocked by some package installation at booting time. For example, when installing `tzdata`:
d6a70383b0c3b244e62553aba12c51e

Since we are already root during the booting time, there is also no need to add `sudo`  there. 

To reproduce, try the following `build.env`:
```
def build():
    base(os="ubuntu20.04", language="python3")
    # config.pip_index(url = "https://pypi.tuna.tsinghua.edu.cn/simple")
    install.apt_packages(name = [
        "tzdata",
    ])
    shell("zsh")
```

### CODE REVIEW

**Comment by kemingy** [comment]
Please rebase the tensorchord/envd:main.

**Comment by oubotong** [comment]
> Please rebase the tensorchord/envd:main.

done

**Review by kemingy — APPROVED** [review]
LGTM. cc @gaocegege

**Comment by gaocegege** [comment]
@allcontributors Please add @oubotong for the code contribution!

**Pull request merged**
