### PR TITLE
ci: Disable github action's auto merge

### PR DESCRIPTION
**Pull request by Xuanwo**
As discussed in https://github.com/tensorchord/envd/pull/309

### CODE REVIEW

**Comment by gaocegege** [comment]
Let's hold to see if there is another way. Thanks for the PR!

**Comment by Xuanwo** [comment]
For reference, go-storage use's GitHub action runner to auto-merge deps related PRs too: https://github.com/beyondstorage/go-storage/blob/master/.github/workflows/auto-merge.yml

**Comment by Xuanwo** [comment]
Something to highlight:

- `on: pull_request_target`: Make sure the action is running target on the main branch's action.
- `make build`: go-storage has some code generate work to do
- `--auto`: Merge PR after all checks passed

**Comment by gaocegege** [comment]
You added a token for the bot `ROBOT_GITHUB_TOKEN` to resolve the issue, LGTM

**Pull request closed without merging**
