### PR TITLE
doc: v1

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

cc @VoVAllen 

It's still ugly. The class method has exactly the same indent as a normal function or a class object. Not sure if we can fix it.

### CODE REVIEW

**Comment by VoVAllen** [comment]
I think it's set at https://github.com/tensorchord/envd-docs/blob/main/hack/api/render.py#L37-L43

**Comment by VoVAllen** [comment]
You can change it if needed

**Comment by kemingy** [comment]
> I think it's set at https://github.com/tensorchord/envd-docs/blob/main/hack/api/render.py#L37-L43

Yes, but the header level is not sufficient. I wonder if this can generate the indents like the Python sphinx doc: https://0b01001001.github.io/spectree/plugins.html

We can merge this one and find a better way letter for the envd-doc repo.

**Comment by VoVAllen** [comment]
I think we don't need to make them as sub class. Does sub module work?

**Comment by kemingy** [comment]
This change should work with https://github.com/tensorchord/envd-docs/pull/206.

I hope we can add the module path to the function title, but sadly there is a bug in the https://github.com/NiklasRosenstein/pydoc-markdown/issues/276

**Comment by gaocegege** [comment]
Could you please give a preview link here?

**Comment by gaocegege** [comment]
About the markdown or html generated by the v1 API

**Comment by kemingy** [comment]
image

**Comment by kemingy** [comment]
Screenshot updated. I guess we can also patch the pydoc-markdown if necessary.

**Comment by gaocegege** [comment]
I am wondering where to tell users that the default version is v0, and they can use `# syntax=v1` to move to v1.

**Comment by kemingy** [comment]
> I am wondering where to tell users that the default version is v0, and they can use `# syntax=v1` to move to v1.

I added to every header of the v1 module doc. See the warning in the screenshot.

**Comment by Juni66623** [comment]
Thu

**Pull request merged**
