### PR TITLE
fix: v0 bashrc file

### LINKED ISSUE #1306: bug: v0 dev env doesn't activate envd conda env by default
## Description

The `/home/envd/.bashrc` doesn't contain any conda related init script. It's weird.

V1 works well.

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

* fix #1306

### CODE REVIEW

**Comment by kemingy** [comment]
PTAL @VoVAllen 

The merge operation overrides `/home/envd/.bashrc`. But I don't know why.

**Comment by kemingy** [comment]
* This blocks https://github.com/tensorchord/envd/issues/1255

**Comment by VoVAllen** [comment]
Is the problem fixed in this pr or not?

**Comment by kemingy** [comment]
> Is the problem fixed in this pr or not?

Fixed by putting the "conda activate envd" into the last step of Python. BTW, "conda init bash" will still be written to root bashrc. That may need more refactoring. But I prefer to keep it as it is in v0. V1 doesn't have this issue.

**Review by VoVAllen — APPROVED** [review]
/lgtm

**Pull request merged**
