### PR TITLE
Bootstrap gets error if the envd_buildkitd was stopped before

### PR DESCRIPTION
**Pull request by pingsutw**
Signed-off-by: Kevin Su <pingsutw@apache.org>

Related to https://github.com/tensorchord/envd/issues/397

image

### CODE REVIEW

**Comment by gaocegege** [comment]
Thanks for the contribution!
The tests are flakey. I will rerun it when I get a laptop.
The code itself LGTM!

**Comment by gaocegege** [comment]
Or you can force push to trigger a new build.

**Comment by VoVAllen** [comment]
Shall we try to restart the container here? @gaocegege

**Comment by gaocegege** [comment]
I think it is better not to restart it, since we do not know if the container exits normally. Maybe we can print a warning to tell users they can remove or restart the container, WDYT @pingsutw @VoVAllen @Triple-Z

**Comment by Triple-Z** [comment]
IMO, restart this container is acceptable. Is this container stateful?

**Comment by pingsutw** [comment]
Yes, agreed, the container should restart by users themself.
Added warning. Thanks for the review.

**Review by Triple-Z — APPROVED** [review]
LGTM

**Comment by gaocegege** [comment]
@all-contributors Please add @pingsutw for his code contribution

**Pull request merged**
