### PR TITLE
refact: apt_source, io, config mode

### LINKED ISSUE #844: refact: align the starlark interface
## Description

1. the implementation of `install.system_packages` is apt-get, should we change to `install.apt_packages`? Also, we have `config.apt_source`, not `config.system_source`.
2. `runtime.expose(envd_port, host_port)`, `io.copy(src, dest)`, `io.mount(src, dest)`, should we align the term?
3. `config.pip_index(mode, url, extra_url)`, `config.apt_source(mode, source)`, if `mode` is not supported yet, should move this parameter to the last one instead of the first one?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by kemingy**
Signed-off-by: Keming <kemingyang@tensorchord.ai>

* close #844

### CODE REVIEW

**Review by gaocegege — COMMENTED** [review]
We also need to update envd-docs.

**Comment by gaocegege** [comment]
Could you please open the corresponding PR in envd-docs?

**Comment by kemingy** [comment]
> Could you please open the corresponding PR in envd-docs?

Sure

**Review by gaocegege — APPROVED** [review]

**Comment by kemingy** [comment]
* docs: https://github.com/tensorchord/envd-docs/pull/126
* envdlib: https://github.com/tensorchord/envdlib/pull/5

PTAL

**Comment by gaocegege** [comment]
These three PRs LGTM. We need to merge ASAP to avoid conflicts.

**Pull request merged**
